export const explainerContent = [
  {
    id: 'hero',
    sectionId: 'home',
    navTitle: 'Headline',
    title: 'Why the headline matters',
    microcopy: 'This is the core message—carbon cost is material, our approach cuts it.',
    bullets: [
      'EU ETS is a carbon cost: every tonne of CO₂ your ships emit requires paid allowances.',
      'Big number = real money: high-emitting ships can face seven-figure annual bills if unmanaged.',
      'Our point: stop “paying for exhaust” by automating compliance and cutting fuel burn.',
    ],
  },
  {
    id: 'timeline',
    sectionId: 'timeline',
    navTitle: 'Timeline',
    title: 'CII, EU ETS, FuelEU—what’s the difference?',
    microcopy: 'Three rules shaping both admin work and cost.',
    bullets: [
      'CII: a ship efficiency score. Poor grades can hurt charter rates.',
      'EU ETS: “cap-and-trade” cost per tonne of CO₂ (we show today’s indicative price).',
      'FuelEU: ramps pressure to use cleaner fuels starting 2025.',
      'Together they drive both admin workload and operating cost.',
    ],
  },
  {
    id: 'ets-calculator',
    sectionId: 'ets-calculator',
    navTitle: 'ETS Calculator',
    title: 'What this slider shows',
    microcopy: 'Quick estimate of your allowance bill.',
    bullets: [
      'Move emissions to see your estimated annual EU ETS allowance bill.',
      'Calculation: Annual CO₂ × current allowance price, with a simple 5-year view using a 7% yearly increase.',
      'It’s directional, not an invoice—helps quantify risk fast.',
    ],
  },
  {
    id: 'roi-calculator',
    sectionId: 'roi-calculator',
    navTitle: 'Savings Calculator',
    title: 'Why we show savings, not ROI',
    microcopy: 'Directional savings from small efficiency gains.',
    bullets: [
      'Enter daily fuel, price, and fleet size to see potential annual savings from efficiency gains.',
      'We default to a conservative 3% efficiency improvement, show the range 3–10% on hover.',
      'This is about avoided spend; pricing for our modules appears later so you don’t anchor on cost too early.',
      '“5-Year NPV Saved” discounts future savings to show today’s value.',
    ],
  },
  {
    id: 'case-studies',
    sectionId: 'case-studies',
    navTitle: 'Case Studies',
    title: 'Proof this works',
    microcopy: 'Examples with audited data paths.',
    bullets: [
      'Real vessels, real numbers: fuel cut, reporting time saved, and payback speed.',
      '“DNV certificate on file” means the data path and outputs are verification-ready.',
      'Shows outcomes across different vessel types.',
    ],
  },
  {
    id: 'how-it-works',
    sectionId: 'how-it-works',
    navTitle: 'How It Works',
    title: '3 steps to value',
    microcopy: 'From data capture to verified outputs.',
    bullets: [
      'Factory-installed BLUE BOX™ captures high-quality data.',
      'Secure cloud verification via DNV Veracity streamlines audits.',
      'Live dashboards automate MRV/CII/ETS and surface fuel-saving opportunities.',
    ],
  },
  {
    id: 'pricing',
    sectionId: 'pricing',
    navTitle: 'Pricing',
    title: 'What you pay for',
    microcopy: 'Indicative subscription and hardware.',
    bullets: [
      'Compliance Core (indicative €15k/year): MRV, CII, ETS reporting.',
      'Optional Fuel-Plus (indicative +€5k/year): design-twin insights and optimization analytics.',
      'One-off hardware (indicative €30k): factory install reduces retrofit friction and downtime.',
    ],
  },
  {
    id: 'cta',
    sectionId: 'audit-cta',
    navTitle: 'Fleet Audit',
    title: 'Why we ask for 20 minutes',
    microcopy: 'Short call to quantify your opportunity.',
    bullets: [
      'We benchmark your situation against peers and quantify near-term wins.',
      'You leave with a simple roadmap, cost exposure view, and a recommended pilot.',
    ],
  },
];
